name: cargo-semver-checks

on:
  pull_request:
    paths: ['**/Cargo.toml']
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # pin@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2
